- name: get pip
  apt:
    name: python-pip

  # http://en.enisozgen.com/ansible-check-is-command-exist/
- name: Check is aws installed
  shell: command -v aws >/dev/null 2>&1
  register: is_aws_exist
  ignore_errors: yes

- name: get aws cli
  pip:
    name: awscli
  when: is_aws_exist.rc != 0

- name: make aws config dir
  file:
    path: "{{ s3_sync_agent_homedir }}/.aws"
    state: directory

- name: configure aws cli
  template:
    src: templates/awsconfig.j2
    dest: "{{ s3_sync_agent_homedir }}/.aws/config"

- name: ensure the backup user exists
  user:
    name: "{{ s3_sync_agent_linux_username }}"
    shell: /bin/bash
  when: s3_sync_agent_linux_username != 'root'

- name: ensure user owns home (for ~/.aws/credentials)
  file:
    path: "{{ s3_sync_agent_homedir }}"
    group: "{{ s3_sync_agent_linux_username }}"
    owner: "{{ s3_sync_agent_linux_username }}"
    mode: "0755"
    recurse: yes
  when: s3_sync_agent_linux_username != 'root'
